on:
  push:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: windows-latest
    env:
      MY_ENV: "env value 01"
    steps:
      - name: run action - 1st
        shell: powershell
        run: echo ${{ env.MY_ENV }}
        
      - name: Set environment variable using Environment File
        run: |
          echo "MY_ENV=env value 02" >> $GITHUB_ENV
          echo $GITHUB_ENV
