on:
  push:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      MY_ENV: "env value 01"
    steps:
      - name: run action - 1st
        uses: actionOrg/actionRepo@master
        with:
          input: ${{ env.MY_ENV }}  # the input value is "env value 01"
      - name: update env
        run: echo "::set-env name=MY_ENV::env value 02"

      - name: run action - 2nd
        uses: actionOrg/actionRepo@master
        with:
          input: ${{ env.MY_ENV }}  # the input value is "env value 02"
