name: my workflow

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      shell: powershell
      run: |
        $env:GITHUB_SHA_SHORT = $env:GITHUB_SHA.Substring(0,6)
        echo "GITHUB_SHA_SHORT=$($env:GITHUB_SHA_SHORT)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Test
      shell: powershell
      run: echo $env:GITHUB_SHA_SHORT
