name: my workflow

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: create new file
      shell: powershell
      run: |
        ni abc.txt
        echo "arjun goel" >> abc.txt
        
    - name: Set env
      shell: powershell
      run: |
        echo "GITHUB_TAG_VERSION=$(cat abc.txt)" >> $GITHUB_ENV
        # $env:GITHUB_SHA_SHORT = $env:GITHUB_SHA.Substring(0,6)
        # echo "GITHUB_SHA_SHORT=$($env:GITHUB_SHA_SHORT)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Test
      shell: powershell
      run: echo $env:GITHUB_TAG_VERSION
